### ISSUE TITLE
Fix for > 3.1 to Phonegap Build

### ISSUE THREAD

**Issue by cutzenfriend** [phonegap-build/StatusBarPlugin#16]
Can you please make this compatible for Phonegap > 3.1 on Phonegap Build! Without that i can't  build my app on phonegap build :(

**Comment by LuizFeReis** [comment]
Updating it to be compatible with Phonegap 3.3 would be really nice! :+1:

**Comment by red2678** [comment]
Please Please. PhoneGap Build 3.3 support is needed.

**Comment by cutzenfriend** [comment]
I think there are already some pull requests to fix the problem but the repo owner seems to be not to be interested :-1:

**Comment by bau720123** [comment]
+1 @@

**Comment by fortress-of-solitude** [comment]
Pretty Please Bob!

**Comment by kwoxford** [comment]
Yes, please fix it!

**Comment by jieves** [comment]
I'm waiting too

**Comment by cutzenfriend** [comment]
Please guys this is really important for me.

**Comment by FedericoRoffiNektan** [comment]
+1

**Comment by mldahl** [comment]
Pretty sure this repo was abandon shortly after the plug-in was submitted to Build.  I think somebody in the know is going to have to fork it, merge the pull request, and re-submit as a new plug-in to PhoneGap Build.

**Comment by cutzenfriend** [comment]
I don't know how to develop phonegap plugins @mldahl could you do that?

i just asked the guys from phonegap-build on twitter....

**Comment by mldahl** [comment]
Neither do I.  I need this as well.

**Comment by cutzenfriend** [comment]
I mean it's the 8th most used plugin.... i'm sure there will be someone who can do it :(

**Comment by kwoxford** [comment]
If it's so heavily used why isn't it a standard feature of PG?

Kim

**Comment by cutzenfriend** [comment]
They just answered me on Twitter ;)

See: http://c.2fq.de/SPLb/5Tuq7dbS

**Comment by wildabeast** [comment]
Sorry guys, @bobeast has left the PGB team and we neglected to reassign management of this plugin. Will get this updated.

**Comment by LuizFeReis** [comment]
Nice :)

**Comment by bau720123** [comment]
really thanks @wildabeast

**Comment by wildabeast** [comment]
Done, and seems to be working with 3.3.0 (and yes it was disabled for a few hours their, sorry about that).

**Comment by jieves** [comment]
Hi,

I just integrated the plugin in my App (built with Phonegap 3.3.0).
I'm still getting a strange behaviour when I start the App (iOS7) in landscape-mode: the statusbar overlaps part of the screen : full height and half of the screen.

See :  http://tinyurl.com/nluoama

I'm using following settings in my code  :

StatusBar.overlaysWebView(false);
StatusBar.styleLightContent();
StatusBar.backgroundColorByHexString("#FE0000");

Can someone help me out please ?

**Comment by red2678** [comment]
Ryan (@wildabeast) man you rock. Thanks so much!

**Comment by jieves** [comment]
Can anyone help me out please .. I would really like to get some solution for this problem :

Hi,

I just integrated the plugin in my App (built with Phonegap 3.3.0).
I'm still getting a strange behaviour when I start the App (iOS7) in landscape-mode: the statusbar overlaps part of the screen : full height and half of the screen.

See : http://tinyurl.com/nluoama

I'm using following settings in my code :

StatusBar.overlaysWebView(false);
StatusBar.styleLightContent();
StatusBar.backgroundColorByHexString("#FE0000");

Can someone help me out please ?

**Comment by bau720123** [comment]
to @jieves 
this plugin maybe can fix by @wildabeast after a few or some times
I am just waiting too ^^

**Comment by jieves** [comment]
Hmmmz , why isn't anyone seeing my message ?
I tried mailing @wildabeast , but I got return receipt error instead. The mailadress on his page is not correct ?

Isn't there anyone who is responsable for this plugin ?

Can anyone help me out please .. I would really like to get some solution for this problem :

Hi,

I just integrated the plugin in my App (built with Phonegap 3.3.0).
I'm still getting a strange behaviour when I start the App (iOS7) in landscape-mode: the statusbar overlaps part of the screen : full height and half of the screen.

See : http://tinyurl.com/nluoama

I'm using following settings in my code :

StatusBar.overlaysWebView(false);
StatusBar.styleLightContent();
StatusBar.backgroundColorByHexString("#FE0000");

Can someone help me out please ?

**Comment by cutzenfriend** [comment]
I would suggest You Open a ticket with the guys from phonegap Build directly! This is how i reached them for fixing this Plugin for 3.3

Von meinem iPhone gesendet

**Comment by jieves** [comment]
Hi,

Do you mean on this page ?  http://community.phonegap.com/nitobi

Kind regards
Joost

Verstuurd vanaf mijn iPad

**Comment by cutzenfriend** [comment]
Yes. :)
An 16. Februar 2014 at 20:47:36, jieves (notifications@github.com) schrieb:

Hi,

Do you mean on this page ? http://community.phonegap.com/nitobi

Kind regards
Joost

Verstuurd vanaf mijn iPad

**Comment by jieves** [comment]
Done.

Let's hope someone will pick it up.

Kind regards
Joost

Verstuurd vanaf mijn iPad

**Comment by wildabeast** [comment]
@jieves it sounds like you're experiencing to issue #4 -- trying to figure out what's causing the landscape startup issue as we speak. Follow there for updates.

**Comment by jieves** [comment]
Thank you very much for picking this up ! I'm looking forward to a solution or workaround.

**Comment by jieves** [comment]
Hi,
@wildabeast : would you be so kind to give me an update please.
Would you be able to provide a solution at short term ?

**Comment by wildabeast** [comment]
@jieves still working on a solution, hopefully early next week.

Please move your discussion to #4.
